-- Exercise library.
-- Generated from src/engine/exercises.ts by scripts/generate-exercise-seed.ts.
-- Do not edit by hand. Change the module and regenerate.

ALTER TABLE exercises ADD COLUMN family TEXT;
ALTER TABLE exercises ADD COLUMN main_lift TEXT;

DELETE FROM exercise_supersets;
DELETE FROM exercise_substitutions;
DELETE FROM exercises;

INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('bb_bench','Flat barbell bench press',NULL,'horizontal_push','["chest"]','["triceps","shoulders"]','["barbell","bench","rack"]','barbell',3,2,0,'["shoulder"]','["Shoulder blades pulled back and down","Bar touches the lower chest","Drive the feet into the floor"]','bench_press','bench');
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('db_bench','Flat dumbbell bench press',NULL,'horizontal_push','["chest"]','["triceps","shoulders"]','["dumbbell","bench"]','dumbbell',2,1,0,NULL,NULL,'bench_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('machine_chest_press','Chest press machine',NULL,'horizontal_push','["chest"]','["triceps","shoulders"]','["machine"]','machine',1,1,0,NULL,NULL,'bench_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('smith_bench','Smith machine bench press',NULL,'horizontal_push','["chest"]','["triceps","shoulders"]','["smith","bench"]','smith',2,1,0,NULL,NULL,'bench_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('cable_press_flat','Flat cable chest press',NULL,'horizontal_push','["chest"]','["triceps","shoulders"]','["cable"]','cable',2,1,0,NULL,NULL,'bench_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('bb_incline','Incline barbell bench press',NULL,'horizontal_push','["chest"]','["shoulders","triceps"]','["barbell","incline_bench","rack"]','barbell',3,2,0,'["shoulder"]',NULL,'incline_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('db_incline','Incline dumbbell press',NULL,'horizontal_push','["chest"]','["shoulders","triceps"]','["dumbbell","incline_bench"]','dumbbell',2,1,0,NULL,NULL,'incline_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('machine_incline_press','Incline press machine',NULL,'horizontal_push','["chest"]','["shoulders","triceps"]','["machine"]','machine',1,1,0,NULL,NULL,'incline_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('bb_decline','Decline barbell bench press',NULL,'horizontal_push','["chest"]','["triceps"]','["barbell","decline_bench","rack"]','barbell',3,2,0,'["shoulder"]',NULL,'decline_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('db_decline','Decline dumbbell press',NULL,'horizontal_push','["chest"]','["triceps"]','["dumbbell","decline_bench"]','dumbbell',2,1,0,NULL,NULL,'decline_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('dip_chest','Chest dip',NULL,'horizontal_push','["chest"]','["triceps","shoulders"]','["dip_station","bodyweight"]','bodyweight',3,1,0,'["shoulder"]',NULL,'decline_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('pushup','Push-up',NULL,'horizontal_push','["chest"]','["triceps","shoulders","abs"]','["bodyweight"]','bodyweight',1,1,0,NULL,NULL,'bench_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('band_chest_press','Banded chest press',NULL,'horizontal_push','["chest"]','["triceps","shoulders"]','["band"]','band',1,1,0,NULL,NULL,'bench_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('cable_fly_mid','Cable fly',NULL,'isolation','["chest"]',NULL,'["cable"]','cable',2,1,0,NULL,NULL,'chest_fly',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('cable_fly_high','Decline cable fly, high to low','["High to low cable fly","Decline cable fly"]','isolation','["chest"]',NULL,'["cable"]','cable',2,1,0,NULL,NULL,'chest_fly',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('cable_fly_low','Incline cable fly, low to high','["Low to high cable fly"]','isolation','["chest"]',NULL,'["cable"]','cable',2,1,0,NULL,NULL,'chest_fly',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('db_fly','Flat dumbbell fly',NULL,'isolation','["chest"]',NULL,'["dumbbell","bench"]','dumbbell',2,1,0,'["shoulder"]',NULL,'chest_fly',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('db_fly_decline','Decline dumbbell fly',NULL,'isolation','["chest"]',NULL,'["dumbbell","decline_bench"]','dumbbell',2,1,0,'["shoulder"]',NULL,'chest_fly',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('pec_deck','Pec deck',NULL,'isolation','["chest"]',NULL,'["machine"]','machine',1,1,0,NULL,NULL,'chest_fly',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('bb_row','Barbell bent-over row',NULL,'horizontal_pull','["back"]','["biceps","rear_delts"]','["barbell"]','barbell',3,2,0,'["lower_back"]','["Hinge to about 45 degrees and hold it","Pull to the belly button, not the chest"]','row',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('db_row','One-arm dumbbell row',NULL,'horizontal_pull','["back"]','["biceps","rear_delts"]','["dumbbell","bench"]','dumbbell',2,1,1,NULL,NULL,'row',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('chest_supported_row_db','Chest supported dumbbell row',NULL,'horizontal_pull','["back"]','["biceps","rear_delts"]','["dumbbell","incline_bench"]','dumbbell',1,1,0,NULL,NULL,'row',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('machine_row','Chest supported row machine',NULL,'horizontal_pull','["back"]','["biceps","rear_delts"]','["machine"]','machine',1,1,0,NULL,NULL,'row',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('cable_row','Seated cable row',NULL,'horizontal_pull','["back"]','["biceps","rear_delts"]','["cable"]','cable',1,1,0,NULL,NULL,'row',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('tbar_row','Landmine row','["T-bar row"]','horizontal_pull','["back"]','["biceps","rear_delts"]','["landmine","barbell"]','barbell',3,1,0,'["lower_back"]',NULL,'row',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('seal_row','Seal row',NULL,'horizontal_pull','["back"]','["biceps","rear_delts"]','["barbell","bench"]','barbell',3,3,0,NULL,NULL,'row',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('inverted_row','Inverted row',NULL,'horizontal_pull','["back"]','["biceps","rear_delts"]','["barbell","rack","bodyweight"]','bodyweight',2,1,0,NULL,NULL,'row',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('band_row','Banded seated row',NULL,'horizontal_pull','["back"]','["biceps","rear_delts"]','["band"]','band',1,1,0,NULL,NULL,'row',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('pullup','Pull-up',NULL,'vertical_pull','["back"]','["biceps"]','["pullup_bar","bodyweight"]','bodyweight',3,1,0,NULL,NULL,'pulldown',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('chinup','Chin-up',NULL,'vertical_pull','["back"]','["biceps"]','["pullup_bar","bodyweight"]','bodyweight',3,1,0,NULL,NULL,'pulldown',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('lat_pulldown','Lat pulldown',NULL,'vertical_pull','["back"]','["biceps"]','["cable"]','cable',1,1,0,NULL,NULL,'pulldown',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('machine_pulldown','Pulldown machine',NULL,'vertical_pull','["back"]','["biceps"]','["machine"]','machine',1,1,0,NULL,NULL,'pulldown',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('band_pulldown','Banded pulldown',NULL,'vertical_pull','["back"]','["biceps"]','["band"]','band',1,1,0,NULL,NULL,'pulldown',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('straight_arm_pulldown','Straight-arm pulldown',NULL,'isolation','["back"]',NULL,'["cable"]','cable',2,1,0,NULL,NULL,'pullover',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('db_pullover','Dumbbell pullover',NULL,'isolation','["back"]','["chest"]','["dumbbell","bench"]','dumbbell',2,1,0,'["shoulder"]',NULL,'pullover',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('rack_pull','Rack pull',NULL,'hinge','["back"]','["hamstrings","glutes"]','["barbell","rack"]','barbell',3,2,0,'["lower_back"]',NULL,'rack_pull',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('bb_ohp','Standing barbell overhead press',NULL,'vertical_push','["shoulders"]','["triceps"]','["barbell","rack"]','barbell',3,2,0,'["shoulder"]','["Squeeze the glutes so the ribs stay down","Push the head through once the bar clears"]','overhead_press','ohp');
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('db_shoulder_press','Seated dumbbell shoulder press',NULL,'vertical_push','["shoulders"]','["triceps"]','["dumbbell","bench"]','dumbbell',2,1,0,NULL,NULL,'overhead_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('machine_shoulder_press','Shoulder press machine',NULL,'vertical_push','["shoulders"]','["triceps"]','["machine"]','machine',1,1,0,NULL,NULL,'overhead_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('smith_ohp','Smith machine overhead press',NULL,'vertical_push','["shoulders"]','["triceps"]','["smith"]','smith',2,1,0,NULL,NULL,'overhead_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('landmine_press','Landmine press',NULL,'vertical_push','["shoulders"]','["triceps","chest"]','["landmine","barbell"]','barbell',2,1,1,NULL,NULL,'overhead_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('arnold_press','Arnold press',NULL,'vertical_push','["shoulders"]','["triceps"]','["dumbbell","bench"]','dumbbell',3,1,0,'["shoulder"]',NULL,'overhead_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('db_lateral_raise','Dumbbell lateral raise',NULL,'isolation','["shoulders"]',NULL,'["dumbbell"]','dumbbell',1,1,0,NULL,NULL,'lateral_raise',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('cable_lateral_raise','Cable lateral raise',NULL,'isolation','["shoulders"]',NULL,'["cable"]','cable',2,1,1,NULL,NULL,'lateral_raise',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('machine_lateral_raise','Lateral raise machine',NULL,'isolation','["shoulders"]',NULL,'["machine"]','machine',1,1,0,NULL,NULL,'lateral_raise',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('band_lateral_raise','Banded lateral raise',NULL,'isolation','["shoulders"]',NULL,'["band"]','band',1,1,0,NULL,NULL,'lateral_raise',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('db_front_raise','Dumbbell front raise',NULL,'isolation','["shoulders"]',NULL,'["dumbbell"]','dumbbell',1,1,0,'["shoulder"]',NULL,'front_raise',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('upright_row','Upright row',NULL,'isolation','["shoulders"]','["rear_delts"]','["barbell"]','barbell',2,1,0,'["shoulder"]',NULL,'front_raise',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('db_rear_fly','Bent-over dumbbell rear delt fly',NULL,'isolation','["rear_delts"]',NULL,'["dumbbell"]','dumbbell',2,1,0,NULL,NULL,'rear_delt_fly',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('cable_rear_fly','Cable rear delt fly',NULL,'isolation','["rear_delts"]',NULL,'["cable"]','cable',2,1,0,NULL,NULL,'rear_delt_fly',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('reverse_pec_deck','Reverse pec deck',NULL,'isolation','["rear_delts"]',NULL,'["machine"]','machine',1,1,0,NULL,NULL,'rear_delt_fly',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('face_pull','Face pull',NULL,'isolation','["rear_delts"]','["back"]','["cable"]','cable',2,1,0,NULL,NULL,'face_pull',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('band_pull_apart','Band pull-apart',NULL,'isolation','["rear_delts"]',NULL,'["band"]','band',1,1,0,NULL,NULL,'rear_delt_fly',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('close_grip_bench','Close grip bench press',NULL,'horizontal_push','["triceps"]','["chest","shoulders"]','["barbell","bench","rack"]','barbell',3,2,0,NULL,NULL,'close_grip_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('skullcrusher','EZ bar skullcrusher',NULL,'isolation','["triceps"]',NULL,'["ez_bar","bench"]','barbell',2,1,0,'["elbow"]',NULL,'triceps_overhead',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('cable_pushdown','Cable triceps pushdown',NULL,'isolation','["triceps"]',NULL,'["cable"]','cable',1,1,0,NULL,NULL,'pushdown',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('rope_pushdown','Rope pushdown',NULL,'isolation','["triceps"]',NULL,'["cable"]','cable',1,1,0,NULL,NULL,'pushdown',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('overhead_cable_ext','Overhead cable triceps extension',NULL,'isolation','["triceps"]',NULL,'["cable"]','cable',2,1,0,NULL,NULL,'triceps_overhead',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('db_overhead_ext','Dumbbell overhead triceps extension',NULL,'isolation','["triceps"]',NULL,'["dumbbell"]','dumbbell',2,1,0,'["elbow"]',NULL,'triceps_overhead',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('dip_triceps','Triceps dip',NULL,'vertical_push','["triceps"]','["chest"]','["dip_station","bodyweight"]','bodyweight',3,1,0,'["shoulder"]',NULL,'close_grip_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('bench_dip','Bench dip',NULL,'isolation','["triceps"]',NULL,'["bench","bodyweight"]','bodyweight',1,1,0,'["shoulder"]',NULL,'pushdown',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('machine_triceps','Triceps extension machine',NULL,'isolation','["triceps"]',NULL,'["machine"]','machine',1,1,0,NULL,NULL,'pushdown',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('band_pushdown','Banded pushdown',NULL,'isolation','["triceps"]',NULL,'["band"]','band',1,1,0,NULL,NULL,'pushdown',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('diamond_pushup','Diamond push-up',NULL,'horizontal_push','["triceps"]','["chest"]','["bodyweight"]','bodyweight',2,1,0,NULL,NULL,'close_grip_press',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('bb_curl','Barbell curl',NULL,'isolation','["biceps"]',NULL,'["barbell"]','barbell',2,1,0,'["wrist"]',NULL,'curl',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('ez_curl','EZ bar curl',NULL,'isolation','["biceps"]',NULL,'["ez_bar"]','barbell',1,1,0,NULL,NULL,'curl',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('db_curl','Dumbbell curl',NULL,'isolation','["biceps"]',NULL,'["dumbbell"]','dumbbell',1,1,0,NULL,NULL,'curl',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('hammer_curl','Hammer curl',NULL,'isolation','["biceps"]','["forearms"]','["dumbbell"]','dumbbell',1,1,0,NULL,NULL,'neutral_curl',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('incline_db_curl','Incline dumbbell curl',NULL,'isolation','["biceps"]',NULL,'["dumbbell","incline_bench"]','dumbbell',2,1,0,NULL,NULL,'curl',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('cable_curl','Cable curl',NULL,'isolation','["biceps"]',NULL,'["cable"]','cable',1,1,0,NULL,NULL,'curl',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('preacher_curl','Preacher curl',NULL,'isolation','["biceps"]',NULL,'["ez_bar","bench"]','barbell',2,1,0,'["elbow"]',NULL,'curl',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('machine_curl','Biceps curl machine',NULL,'isolation','["biceps"]',NULL,'["machine"]','machine',1,1,0,NULL,NULL,'curl',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('band_curl','Banded curl',NULL,'isolation','["biceps"]',NULL,'["band"]','band',1,1,0,NULL,NULL,'curl',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('concentration_curl','Concentration curl',NULL,'isolation','["biceps"]',NULL,'["dumbbell","bench"]','dumbbell',1,1,1,NULL,NULL,'curl',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('bb_back_squat','Barbell back squat',NULL,'squat','["quads"]','["glutes","hamstrings"]','["barbell","rack"]','barbell',4,2,0,'["lower_back"]','["Brace before you unrack, not after","Knees track over the middle of the foot","Depth before load"]','squat','squat');
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('bb_front_squat','Front squat',NULL,'squat','["quads"]','["glutes","abs"]','["barbell","rack"]','barbell',5,3,0,NULL,NULL,'squat',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('goblet_squat','Goblet squat',NULL,'squat','["quads"]','["glutes"]','["dumbbell"]','dumbbell',1,1,0,NULL,NULL,'squat',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('hack_squat','Hack squat machine',NULL,'squat','["quads"]','["glutes"]','["machine"]','machine',2,1,0,NULL,NULL,'squat',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('leg_press','Leg press',NULL,'squat','["quads"]','["glutes","hamstrings"]','["machine"]','machine',1,1,0,NULL,NULL,'squat',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('smith_squat','Smith machine squat',NULL,'squat','["quads"]','["glutes"]','["smith"]','smith',2,1,0,NULL,NULL,'squat',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('belt_squat','Safety bar squat',NULL,'squat','["quads"]','["glutes"]','["specialty_bar","rack"]','barbell',3,2,0,NULL,NULL,'squat',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('split_squat','Bulgarian split squat',NULL,'lunge','["quads"]','["glutes"]','["dumbbell","bench"]','dumbbell',3,1,1,'["knee"]',NULL,'lunge',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('walking_lunge','Walking lunge',NULL,'lunge','["quads"]','["glutes"]','["dumbbell"]','dumbbell',2,1,1,'["knee"]',NULL,'lunge',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('step_up','Step-up',NULL,'lunge','["quads"]','["glutes"]','["dumbbell","box"]','dumbbell',2,1,1,'["knee"]',NULL,'lunge',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('leg_extension','Leg extension',NULL,'isolation','["quads"]',NULL,'["machine"]','machine',1,1,0,'["knee"]',NULL,'leg_extension',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('bw_squat','Bodyweight squat',NULL,'squat','["quads"]','["glutes"]','["bodyweight"]','bodyweight',1,1,0,NULL,NULL,'squat',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('band_squat','Banded squat',NULL,'squat','["quads"]','["glutes"]','["band"]','band',1,1,0,NULL,NULL,'squat',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('sled_push','Sled push',NULL,'carry','["quads"]','["glutes","calves"]','["sled"]','bodyweight',1,1,0,NULL,NULL,'carry',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('bb_deadlift','Conventional deadlift',NULL,'hinge','["hamstrings","glutes"]','["back"]','["barbell"]','barbell',4,2,0,'["lower_back"]','["Take the slack out of the bar before you pull","Push the floor away rather than lifting the bar"]','deadlift','deadlift');
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('sumo_deadlift','Sumo deadlift',NULL,'hinge','["hamstrings","glutes"]','["quads"]','["barbell"]','barbell',4,2,0,'["lower_back","hip"]',NULL,'deadlift',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('trap_bar_dl','Trap bar deadlift',NULL,'hinge','["hamstrings","glutes"]','["quads"]','["specialty_bar"]','barbell',2,1,0,'["lower_back"]',NULL,'deadlift',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('rdl','Romanian deadlift',NULL,'hinge','["hamstrings","glutes"]',NULL,'["barbell","rack"]','barbell',3,1,0,'["lower_back"]',NULL,'rdl',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('db_rdl','Dumbbell Romanian deadlift',NULL,'hinge','["hamstrings","glutes"]',NULL,'["dumbbell"]','dumbbell',2,1,0,'["lower_back"]',NULL,'rdl',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('good_morning','Good morning',NULL,'hinge','["hamstrings","glutes"]',NULL,'["barbell","rack"]','barbell',4,2,0,'["lower_back"]',NULL,'rdl',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('lying_leg_curl','Lying leg curl',NULL,'isolation','["hamstrings"]',NULL,'["machine"]','machine',1,1,0,NULL,NULL,'leg_curl_lying',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('seated_leg_curl','Seated leg curl',NULL,'isolation','["hamstrings"]',NULL,'["machine"]','machine',1,1,0,NULL,NULL,'leg_curl_seated',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('nordic_curl','Nordic hamstring curl',NULL,'isolation','["hamstrings"]',NULL,'["bodyweight"]','bodyweight',4,1,0,NULL,NULL,'leg_curl_lying',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('band_leg_curl','Banded leg curl',NULL,'isolation','["hamstrings"]',NULL,'["band"]','band',1,1,0,NULL,NULL,'leg_curl_lying',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('kb_swing','Kettlebell swing',NULL,'hinge','["hamstrings","glutes"]',NULL,'["kettlebell"]','kettlebell',3,1,0,'["lower_back"]',NULL,'rdl',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('hip_thrust','Barbell hip thrust',NULL,'hinge','["glutes","hamstrings"]',NULL,'["barbell","bench"]','barbell',2,2,0,NULL,NULL,'hip_thrust',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('db_hip_thrust','Dumbbell hip thrust',NULL,'hinge','["glutes","hamstrings"]',NULL,'["dumbbell","bench"]','dumbbell',1,1,0,NULL,NULL,'hip_thrust',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('machine_hip_thrust','Hip thrust machine',NULL,'hinge','["glutes","hamstrings"]',NULL,'["machine"]','machine',1,1,0,NULL,NULL,'hip_thrust',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('glute_bridge','Glute bridge',NULL,'hinge','["glutes","hamstrings"]',NULL,'["bodyweight"]','bodyweight',1,1,0,NULL,NULL,'hip_thrust',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('cable_pull_through','Cable pull-through',NULL,'hinge','["glutes","hamstrings"]',NULL,'["cable"]','cable',2,1,0,NULL,NULL,'hip_thrust',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('cable_kickback','Cable glute kickback',NULL,'isolation','["glutes"]',NULL,'["cable"]','cable',1,1,1,NULL,NULL,'kickback',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('back_extension','45 degree back extension',NULL,'hinge','["glutes","hamstrings"]','["back"]','["machine","bodyweight"]','bodyweight',2,1,0,'["lower_back"]',NULL,'back_extension',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('standing_calf_raise','Standing calf raise',NULL,'isolation','["calves"]',NULL,'["machine"]','machine',1,1,0,NULL,NULL,'calf_standing',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('seated_calf_raise','Seated calf raise',NULL,'isolation','["calves"]',NULL,'["machine"]','machine',1,1,0,NULL,NULL,'calf_seated',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('leg_press_calf','Calf press on the leg press',NULL,'isolation','["calves"]',NULL,'["machine"]','machine',1,1,0,NULL,NULL,'calf_standing',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('smith_calf_raise','Smith machine calf raise',NULL,'isolation','["calves"]',NULL,'["smith","box"]','smith',1,1,0,NULL,NULL,'calf_standing',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('db_calf_raise','Dumbbell standing calf raise',NULL,'isolation','["calves"]',NULL,'["dumbbell"]','dumbbell',1,1,0,NULL,NULL,'calf_standing',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('bw_calf_raise','Bodyweight calf raise',NULL,'isolation','["calves"]',NULL,'["bodyweight"]','bodyweight',1,1,0,NULL,NULL,'calf_standing',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('farmers_carry','Farmer''s carry',NULL,'carry','["forearms"]','["abs"]','["dumbbell"]','dumbbell',1,1,0,NULL,NULL,'carry',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('wrist_curl','Dumbbell wrist curl',NULL,'isolation','["forearms"]',NULL,'["dumbbell","bench"]','dumbbell',1,1,0,'["wrist"]',NULL,'wrist',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('reverse_curl','Reverse curl',NULL,'isolation','["forearms","biceps"]',NULL,'["ez_bar"]','barbell',1,1,0,NULL,NULL,'neutral_curl',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('dead_hang','Dead hang',NULL,'carry','["forearms"]',NULL,'["pullup_bar","bodyweight"]','bodyweight',1,1,0,NULL,NULL,'carry',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('cable_crunch','Cable crunch',NULL,'isolation','["abs"]',NULL,'["cable"]','cable',1,1,0,NULL,NULL,'ab_flexion',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('hanging_leg_raise','Hanging leg raise',NULL,'isolation','["abs"]',NULL,'["pullup_bar","bodyweight"]','bodyweight',3,1,0,NULL,NULL,'leg_raise',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('machine_crunch','Abdominal crunch machine',NULL,'isolation','["abs"]',NULL,'["machine"]','machine',1,1,0,NULL,NULL,'ab_flexion',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('weighted_situp','Decline sit-up',NULL,'isolation','["abs"]',NULL,'["decline_bench","bodyweight"]','bodyweight',2,1,0,'["lower_back"]',NULL,'ab_flexion',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('ab_wheel','Ab wheel rollout',NULL,'isolation','["abs"]',NULL,'["bodyweight"]','bodyweight',3,1,0,'["lower_back"]',NULL,'ab_brace',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('plank','Plank',NULL,'isolation','["abs"]',NULL,'["bodyweight"]','bodyweight',1,1,0,NULL,NULL,'ab_brace',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('dead_bug','Dead bug',NULL,'isolation','["abs"]',NULL,'["bodyweight"]','bodyweight',1,1,0,NULL,NULL,'ab_brace',NULL);
INSERT INTO exercises (id,name,aliases,movement_pattern,prime_movers,secondary_movers,equipment,loading_type,skill_level,setup_complexity,unilateral,contraindications,coaching_cues,family,main_lift) VALUES ('pallof_press','Pallof press',NULL,'isolation','["abs"]',NULL,'["cable"]','cable',2,1,0,NULL,NULL,'ab_brace',NULL);

INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_bench','db_bench',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_bench','machine_chest_press',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_bench','smith_bench',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_bench','cable_press_flat',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_bench','bb_bench',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_bench','machine_chest_press',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_bench','cable_press_flat',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_bench','pushup',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_chest_press','db_bench',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_chest_press','cable_press_flat',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_chest_press','smith_bench',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_chest_press','pushup',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('smith_bench','machine_chest_press',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('smith_bench','db_bench',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('smith_bench','bb_bench',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_press_flat','machine_chest_press',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_press_flat','db_bench',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_press_flat','pushup',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_incline','db_incline',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_incline','machine_incline_press',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_incline','cable_fly_low',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_incline','smith_bench',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_incline','bb_incline',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_incline','machine_incline_press',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_incline','cable_fly_low',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_incline','pushup',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_incline_press','db_incline',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_incline_press','cable_fly_low',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_incline_press','machine_chest_press',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_decline','db_decline',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_decline','dip_chest',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_decline','cable_fly_high',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_decline','machine_chest_press',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_decline','bb_decline',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_decline','dip_chest',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_decline','cable_fly_high',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_decline','db_bench',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('dip_chest','db_decline',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('dip_chest','cable_fly_high',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('dip_chest','machine_chest_press',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('pushup','db_bench',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('pushup','machine_chest_press',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('pushup','band_chest_press',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_chest_press','pushup',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_chest_press','cable_press_flat',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_chest_press','db_bench',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_fly_mid','pec_deck',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_fly_mid','db_fly',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_fly_mid','cable_fly_high',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_fly_mid','cable_fly_low',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_fly_high','db_fly_decline',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_fly_high','cable_fly_mid',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_fly_high','pec_deck',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_fly_high','db_fly',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_fly_low','cable_fly_mid',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_fly_low','db_fly',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_fly_low','pec_deck',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_fly','cable_fly_mid',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_fly','pec_deck',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_fly','db_fly_decline',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_fly_decline','cable_fly_high',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_fly_decline','db_fly',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_fly_decline','pec_deck',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('pec_deck','cable_fly_mid',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('pec_deck','db_fly',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('pec_deck','cable_fly_high',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_row','chest_supported_row_db',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_row','cable_row',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_row','machine_row',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_row','db_row',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_row','cable_row',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_row','machine_row',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_row','chest_supported_row_db',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_row','bb_row',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('chest_supported_row_db','machine_row',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('chest_supported_row_db','cable_row',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('chest_supported_row_db','db_row',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_row','cable_row',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_row','chest_supported_row_db',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_row','db_row',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_row','machine_row',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_row','chest_supported_row_db',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_row','db_row',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_row','band_row',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('tbar_row','machine_row',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('tbar_row','cable_row',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('tbar_row','db_row',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('seal_row','chest_supported_row_db',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('seal_row','machine_row',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('seal_row','cable_row',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('inverted_row','cable_row',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('inverted_row','band_row',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('inverted_row','db_row',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_row','cable_row',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_row','inverted_row',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_row','db_row',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('pullup','lat_pulldown',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('pullup','chinup',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('pullup','machine_pulldown',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('pullup','band_pulldown',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('chinup','lat_pulldown',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('chinup','pullup',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('chinup','machine_pulldown',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('lat_pulldown','machine_pulldown',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('lat_pulldown','pullup',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('lat_pulldown','band_pulldown',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_pulldown','lat_pulldown',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_pulldown','pullup',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_pulldown','band_pulldown',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_pulldown','lat_pulldown',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_pulldown','machine_pulldown',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_pulldown','pullup',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('straight_arm_pulldown','db_pullover',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('straight_arm_pulldown','lat_pulldown',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_pullover','straight_arm_pulldown',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_pullover','lat_pulldown',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('rack_pull','bb_row',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('rack_pull','machine_row',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('rack_pull','cable_row',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_ohp','db_shoulder_press',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_ohp','machine_shoulder_press',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_ohp','landmine_press',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_ohp','smith_ohp',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_shoulder_press','machine_shoulder_press',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_shoulder_press','bb_ohp',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_shoulder_press','landmine_press',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_shoulder_press','arnold_press',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_shoulder_press','db_shoulder_press',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_shoulder_press','smith_ohp',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_shoulder_press','landmine_press',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('smith_ohp','machine_shoulder_press',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('smith_ohp','db_shoulder_press',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('smith_ohp','bb_ohp',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('landmine_press','db_shoulder_press',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('landmine_press','machine_shoulder_press',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('arnold_press','db_shoulder_press',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('arnold_press','machine_shoulder_press',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_lateral_raise','cable_lateral_raise',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_lateral_raise','machine_lateral_raise',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_lateral_raise','band_lateral_raise',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_lateral_raise','db_lateral_raise',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_lateral_raise','machine_lateral_raise',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_lateral_raise','band_lateral_raise',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_lateral_raise','db_lateral_raise',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_lateral_raise','cable_lateral_raise',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_lateral_raise','db_lateral_raise',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_lateral_raise','cable_lateral_raise',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_front_raise','db_lateral_raise',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_front_raise','cable_lateral_raise',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('upright_row','db_lateral_raise',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('upright_row','cable_lateral_raise',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('upright_row','machine_lateral_raise',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_rear_fly','reverse_pec_deck',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_rear_fly','cable_rear_fly',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_rear_fly','face_pull',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_rear_fly','band_pull_apart',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_rear_fly','reverse_pec_deck',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_rear_fly','face_pull',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_rear_fly','db_rear_fly',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('reverse_pec_deck','cable_rear_fly',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('reverse_pec_deck','db_rear_fly',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('reverse_pec_deck','face_pull',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('face_pull','band_pull_apart',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('face_pull','reverse_pec_deck',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('face_pull','db_rear_fly',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_pull_apart','face_pull',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_pull_apart','db_rear_fly',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_pull_apart','reverse_pec_deck',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('close_grip_bench','dip_triceps',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('close_grip_bench','machine_triceps',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('close_grip_bench','cable_pushdown',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('close_grip_bench','diamond_pushup',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('skullcrusher','overhead_cable_ext',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('skullcrusher','cable_pushdown',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('skullcrusher','db_overhead_ext',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_pushdown','rope_pushdown',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_pushdown','machine_triceps',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_pushdown','band_pushdown',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_pushdown','bench_dip',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('rope_pushdown','cable_pushdown',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('rope_pushdown','machine_triceps',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('rope_pushdown','band_pushdown',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('overhead_cable_ext','db_overhead_ext',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('overhead_cable_ext','skullcrusher',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('overhead_cable_ext','cable_pushdown',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_overhead_ext','overhead_cable_ext',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_overhead_ext','skullcrusher',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_overhead_ext','cable_pushdown',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('dip_triceps','close_grip_bench',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('dip_triceps','bench_dip',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('dip_triceps','machine_triceps',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('dip_triceps','cable_pushdown',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bench_dip','cable_pushdown',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bench_dip','diamond_pushup',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bench_dip','machine_triceps',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_triceps','cable_pushdown',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_triceps','rope_pushdown',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_triceps','bench_dip',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_pushdown','cable_pushdown',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_pushdown','bench_dip',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_pushdown','diamond_pushup',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('diamond_pushup','bench_dip',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('diamond_pushup','cable_pushdown',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('diamond_pushup','close_grip_bench',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_curl','ez_curl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_curl','db_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_curl','cable_curl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_curl','machine_curl',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('ez_curl','db_curl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('ez_curl','cable_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('ez_curl','machine_curl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('ez_curl','bb_curl',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_curl','cable_curl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_curl','ez_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_curl','hammer_curl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_curl','band_curl',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('hammer_curl','db_curl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('hammer_curl','cable_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('hammer_curl','reverse_curl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('incline_db_curl','db_curl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('incline_db_curl','cable_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('incline_db_curl','preacher_curl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_curl','db_curl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_curl','machine_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_curl','ez_curl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_curl','band_curl',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('preacher_curl','machine_curl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('preacher_curl','incline_db_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('preacher_curl','cable_curl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_curl','cable_curl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_curl','db_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_curl','preacher_curl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_curl','db_curl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_curl','cable_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_curl','machine_curl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('concentration_curl','db_curl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('concentration_curl','cable_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('concentration_curl','incline_db_curl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_back_squat','hack_squat',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_back_squat','leg_press',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_back_squat','goblet_squat',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_back_squat','smith_squat',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_front_squat','hack_squat',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_front_squat','goblet_squat',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_front_squat','leg_press',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_front_squat','bb_back_squat',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('goblet_squat','leg_press',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('goblet_squat','bb_back_squat',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('goblet_squat','hack_squat',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('goblet_squat','bw_squat',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('hack_squat','leg_press',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('hack_squat','bb_back_squat',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('hack_squat','smith_squat',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('hack_squat','goblet_squat',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('leg_press','hack_squat',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('leg_press','goblet_squat',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('leg_press','smith_squat',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('leg_press','bb_back_squat',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('smith_squat','hack_squat',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('smith_squat','leg_press',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('smith_squat','bb_back_squat',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('belt_squat','hack_squat',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('belt_squat','leg_press',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('belt_squat','bb_back_squat',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('split_squat','walking_lunge',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('split_squat','step_up',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('split_squat','leg_press',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('split_squat','goblet_squat',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('walking_lunge','split_squat',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('walking_lunge','step_up',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('walking_lunge','leg_press',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('step_up','split_squat',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('step_up','walking_lunge',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('step_up','leg_press',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('leg_extension','leg_press',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('leg_extension','goblet_squat',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('leg_extension','bw_squat',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bw_squat','goblet_squat',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bw_squat','band_squat',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bw_squat','leg_press',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_squat','bw_squat',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_squat','goblet_squat',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_squat','leg_press',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('sled_push','walking_lunge',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('sled_push','leg_press',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_deadlift','trap_bar_dl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_deadlift','rdl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_deadlift','db_rdl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bb_deadlift','lying_leg_curl',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('sumo_deadlift','bb_deadlift',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('sumo_deadlift','trap_bar_dl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('sumo_deadlift','rdl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('trap_bar_dl','bb_deadlift',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('trap_bar_dl','rdl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('trap_bar_dl','lying_leg_curl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('rdl','db_rdl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('rdl','lying_leg_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('rdl','seated_leg_curl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('rdl','cable_pull_through',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_rdl','rdl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_rdl','lying_leg_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_rdl','cable_pull_through',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('good_morning','rdl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('good_morning','seated_leg_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('good_morning','back_extension',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('lying_leg_curl','seated_leg_curl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('lying_leg_curl','nordic_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('lying_leg_curl','band_leg_curl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('lying_leg_curl','db_rdl',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('seated_leg_curl','lying_leg_curl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('seated_leg_curl','nordic_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('seated_leg_curl','band_leg_curl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('nordic_curl','lying_leg_curl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('nordic_curl','seated_leg_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('nordic_curl','db_rdl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_leg_curl','lying_leg_curl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_leg_curl','nordic_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('band_leg_curl','db_rdl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('kb_swing','db_rdl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('kb_swing','cable_pull_through',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('kb_swing','hip_thrust',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('hip_thrust','machine_hip_thrust',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('hip_thrust','db_hip_thrust',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('hip_thrust','glute_bridge',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('hip_thrust','cable_pull_through',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_hip_thrust','hip_thrust',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_hip_thrust','machine_hip_thrust',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_hip_thrust','glute_bridge',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_hip_thrust','hip_thrust',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_hip_thrust','db_hip_thrust',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_hip_thrust','cable_pull_through',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('glute_bridge','db_hip_thrust',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('glute_bridge','hip_thrust',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('glute_bridge','cable_pull_through',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_pull_through','hip_thrust',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_pull_through','db_rdl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_pull_through','glute_bridge',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_kickback','cable_pull_through',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_kickback','glute_bridge',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_kickback','hip_thrust',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('back_extension','glute_bridge',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('back_extension','cable_pull_through',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('back_extension','db_rdl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('standing_calf_raise','smith_calf_raise',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('standing_calf_raise','db_calf_raise',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('standing_calf_raise','leg_press_calf',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('standing_calf_raise','bw_calf_raise',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('seated_calf_raise','standing_calf_raise',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('seated_calf_raise','leg_press_calf',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('seated_calf_raise','db_calf_raise',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('leg_press_calf','standing_calf_raise',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('leg_press_calf','seated_calf_raise',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('leg_press_calf','db_calf_raise',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('smith_calf_raise','standing_calf_raise',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('smith_calf_raise','db_calf_raise',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('smith_calf_raise','bw_calf_raise',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_calf_raise','standing_calf_raise',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_calf_raise','bw_calf_raise',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('db_calf_raise','smith_calf_raise',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bw_calf_raise','db_calf_raise',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('bw_calf_raise','standing_calf_raise',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('farmers_carry','dead_hang',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('farmers_carry','wrist_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('farmers_carry','reverse_curl',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('wrist_curl','reverse_curl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('wrist_curl','farmers_carry',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('wrist_curl','dead_hang',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('reverse_curl','hammer_curl',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('reverse_curl','wrist_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('reverse_curl','farmers_carry',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('dead_hang','farmers_carry',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('dead_hang','wrist_curl',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_crunch','machine_crunch',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_crunch','hanging_leg_raise',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_crunch','weighted_situp',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('cable_crunch','plank',4,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('hanging_leg_raise','cable_crunch',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('hanging_leg_raise','weighted_situp',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('hanging_leg_raise','dead_bug',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_crunch','cable_crunch',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_crunch','weighted_situp',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('machine_crunch','plank',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('weighted_situp','cable_crunch',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('weighted_situp','machine_crunch',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('weighted_situp','dead_bug',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('ab_wheel','plank',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('ab_wheel','cable_crunch',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('ab_wheel','hanging_leg_raise',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('plank','dead_bug',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('plank','pallof_press',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('plank','cable_crunch',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('dead_bug','plank',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('dead_bug','pallof_press',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('dead_bug','cable_crunch',3,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('pallof_press','plank',1,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('pallof_press','dead_bug',2,'equipment');
INSERT INTO exercise_substitutions (exercise_id,substitute_id,rank,reason) VALUES ('pallof_press','cable_crunch',3,'equipment');

